// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        // TODO: FlutterFire CLI로 정식 windows 앱을 등록하기 전까지, UI 확인용
        // 로컬 실행이 막히지 않도록 iOS 설정값을 임시로 재사용한다. 로그인/
        // Firestore 등 실제 백엔드 호출은 정상 동작을 보장하지 않는다.
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnbQKKgj2vxyUI7nbqRj7TJ8HpT4Q8OnI',
    appId: '1:838064162852:android:0c33107cc18fb2191670b1',
    messagingSenderId: '838064162852',
    projectId: 'ai-fashion-assistant-personal',
    storageBucket: 'ai-fashion-assistant-personal.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7zMFfoCqFiXuCxDfQBrQbRovGJEuE-OU',
    appId: '1:838064162852:ios:08688958e7944f8f1670b1',
    messagingSenderId: '838064162852',
    projectId: 'ai-fashion-assistant-personal',
    storageBucket: 'ai-fashion-assistant-personal.firebasestorage.app',
    iosBundleId: 'com.yujaehyuk.fashionai.test3462',
  );
}
